### ISSUE TITLE
Question about the mojito-cli

### ISSUE THREAD

**Issue by happycharlie** [zuc/docker-mojito#1]
Here is how I run the mzuccala/mojito:cli on ubuntu and a web-app is already running on localhost's port 8080 

 **$sudo docker run --rm mzuccala/mojito:cli "demo-create -n Demo1" -e MOJITO_API_HOST=localhost -e MOJITO_API_PORT=8080 -e MOJITO_API_SCHEME=HTTP -e MOJITO_API_USER=admin -e MOJITO_API_PASS=ChangeMe**

However, I got an error message as follow..

**Create demo repository: Demo1
Is a server running on: ?**

Did I do something wrong? Please assist. Thanks a lot.

**Comment by zuc** [comment]
@happycharlie sorry for the late reply! I never received the related notification from GitHub :(

I think this problem is that you are targeting `localhost` from inside a container, therefore your command is trying to hit the container itself instead of the host machine (see [here](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach)).

Hope this helps!
